export type Article = {
  slug: string;
  title: string;
  description: string;
  category: string;
  format: "Explainer" | "Playbook" | "Claim check" | "Data note" | "Checklist";
  series: string;
  readTime: string;
  published: string;
  updated: string;
  evidence: "Primary sources" | "Documented practice" | "Desk analysis";
  audience: string;
  keyTakeaways: string[];
  verdict: string;
  sections: { heading: string; paragraphs: string[]; bullets?: string[] }[];
};

export const articles: Article[] = [
  {
    slug: "how-to-read-an-seo-audit",
    title: "How to read an SEO audit without getting snowed",
    description: "A long PDF is not a strategy. Here is how to separate reproducible findings from expensive formatting and recycled warnings.",
    category: "Buyer defense",
    format: "Playbook",
    series: "Buying SEO",
    readTime: "8 min read",
    published: "July 11, 2026",
    updated: "July 11, 2026",
    evidence: "Documented practice",
    audience: "Owners and marketing leads",
    keyTakeaways: ["Require a reproducible evidence trail", "Separate crawler inventory from expert judgment", "Prioritize by consequence and dependency"],
    verdict: "A useful audit connects every finding to evidence, consequence, priority, and a practical next action.",
    sections: [
      { heading: "Start with the evidence trail", paragraphs: ["Every important finding should tell you which URL, response, template, query, or dataset produced it. Screenshots can help, but they should not replace reproducible evidence.", "If the auditor cannot show you how to see the problem yourself, treat the conclusion as provisional."], bullets: ["Affected URLs or templates", "The method or tool used", "Why the finding matters", "A severity and confidence level"] },
      { heading: "Separate inventory from judgment", paragraphs: ["Crawlers can inventory redirects, headings, canonicals, status codes, and links. The valuable part is deciding which observations matter to this site and this business.", "A 200-row export is evidence collection. It becomes an audit only after prioritization and interpretation."] },
      { heading: "Ask what changes first", paragraphs: ["The audit should identify dependencies and sequence. Indexation work may come before content polishing. Template fixes may beat editing hundreds of pages by hand."], bullets: ["What can be fixed once at the template level?", "What blocks crawling or indexing?", "What affects revenue-critical pages?", "What needs measurement before intervention?"] },
      { heading: "Red flags", paragraphs: ["Be cautious when every issue is urgent, tool scores are presented as business outcomes, or the recommendations could apply unchanged to any website."] },
    ],
  },
  {
    slug: "technical-seo-baseline",
    title: "The technical SEO baseline before you touch content",
    description: "Confirm that the site can be crawled, understood, measured, and repaired before chasing keywords.",
    category: "Technical SEO",
    format: "Checklist",
    series: "Technical baseline",
    readTime: "6 min read",
    published: "July 10, 2026",
    updated: "July 10, 2026",
    evidence: "Documented practice",
    audience: "Operators and technical marketers",
    keyTakeaways: ["Verify the public URL surface", "Make measurement stable before intervention", "Change fewer variables at once"],
    verdict: "A clean baseline does not create demand, but it prevents basic technical ambiguity from poisoning every later experiment.",
    sections: [
      { heading: "Confirm the public surface", paragraphs: ["Inventory the URLs meant for visitors and search systems. Verify that they return the expected status, render meaningful content, and link to one another through ordinary navigation."], bullets: ["Canonical production hostname", "HTTPS behavior", "Status codes", "Index directives", "Internal navigation"] },
      { heading: "Check discovery", paragraphs: ["The XML sitemap should list canonical, public, indexable URLs. robots.txt should communicate crawl preferences without exposing private paths or blocking necessary resources."] },
      { heading: "Make measurement boring", paragraphs: ["Verify Search Console ownership, analytics events, consent behavior, and conversion definitions before making changes. A baseline without dates and definitions is a story, not a measurement."] },
      { heading: "Freeze the shell", paragraphs: ["Avoid changing titles, templates, navigation, hosting, and content simultaneously. Establish a stable shell so later tests have a chance of teaching you something."] },
    ],
  },
  {
    slug: "seo-pricing-without-fairy-tales",
    title: "SEO pricing without the decorative averages",
    description: "Most pricing questions are scope questions wearing a dollar sign. Ask what actually happens after the invoice.",
    category: "Pricing clarity",
    format: "Explainer",
    series: "Buying SEO",
    readTime: "7 min read",
    published: "July 9, 2026",
    updated: "July 9, 2026",
    evidence: "Desk analysis",
    audience: "Owners and procurement teams",
    keyTakeaways: ["Compare delivery models, not retainers", "Expose implementation dependencies", "Define access and ownership before signing"],
    verdict: "Compare the work, access, assumptions, and accountability—not just the monthly number.",
    sections: [
      { heading: "Define the operating model", paragraphs: ["Strategy, implementation, content production, digital PR, local profile management, and reporting are different jobs. A price without a delivery model is not comparable."], bullets: ["Who makes changes?", "Who owns the accounts?", "How much content is included?", "What triggers a re-scope?"] },
      { heading: "Find the hidden dependencies", paragraphs: ["A proposal may assume that your developers ship fixes, your team supplies subject expertise, or your approvals arrive in days. Those assumptions affect both cost and likely progress."] },
      { heading: "Demand useful reporting", paragraphs: ["Reporting should connect work to observable changes, search visibility, qualified actions, and remaining uncertainty. Activity counts alone reward motion rather than outcomes."] },
      { heading: "Contract questions", paragraphs: ["Clarify cancellation, access handoff, content ownership, historical data, third-party fees, and the disposition of accounts when the relationship ends."] },
    ],
  },
  {
    slug: "ranking-guarantees",
    title: "Ranking guarantees are a contract-reading exercise",
    description: "The promise is only as useful as its query set, geography, device context, exclusions, and remedy.",
    category: "Bad SEO patterns",
    format: "Claim check",
    series: "Claim checks",
    readTime: "5 min read",
    published: "July 8, 2026",
    updated: "July 8, 2026",
    evidence: "Primary sources",
    audience: "SEO buyers",
    keyTakeaways: ["Define the exact promised outcome", "Demand a measurement protocol", "Buy controllable work instead of guarantees"],
    verdict: "Treat guarantees as prompts for better questions, never as evidence of competence.",
    sections: [
      { heading: "Interrogate the noun", paragraphs: ["What exactly is being guaranteed: one branded query, a set of commercial terms, local-map visibility, traffic, leads, or revenue? Each is a different claim."] },
      { heading: "Inspect the measurement", paragraphs: ["Rankings vary by location, language, device, time, personalization, and result type. A guarantee without a measurement protocol is mostly theater."], bullets: ["Named query set", "Location and device", "Measurement platform", "Start and end dates", "What happens on failure"] },
      { heading: "Read the escape hatches", paragraphs: ["Look for exclusions tied to approvals, developer capacity, algorithm changes, competitors, site migrations, or content access. Some agreements guarantee only that work continues—not that money returns."] },
      { heading: "Buy controllable work", paragraphs: ["Providers can responsibly promise deliverables, response times, documentation, access, and testing discipline. They cannot control an external ranking system."] },
    ],
  },
  {
    slug: "search-console-is-not-analytics",
    title: "Search Console is not Analytics—and that is useful",
    description: "One shows how Google Search saw and surfaced your pages. The other records configured behavior after visits.",
    category: "Measurement",
    format: "Explainer",
    series: "Measurement without theater",
    readTime: "6 min read",
    published: "July 7, 2026",
    updated: "July 7, 2026",
    evidence: "Primary sources",
    audience: "Analysts and marketing leads",
    keyTakeaways: ["Search, behavior, and revenue are different records", "Expect explainable mismatches", "Design the decision before the dashboard"],
    verdict: "Use Search Console for Google Search visibility and technical evidence; use analytics for configured on-site behavior; use business systems for actual customers.",
    sections: [
      { heading: "Three different records", paragraphs: ["Search Console, web analytics, and your CRM answer different questions. Combining them is useful. Pretending they are interchangeable creates fake certainty."], bullets: ["Search Console: queries, pages, clicks, impressions", "Analytics: configured events and sessions", "CRM or sales system: qualified leads and revenue"] },
      { heading: "Expect mismatches", paragraphs: ["Dates, time zones, attribution, consent, filters, and identity rules differ. Small discrepancies are normal; unexplained large ones deserve investigation."] },
      { heading: "Design the decision first", paragraphs: ["Collect the smallest set of signals that answer a real operating question. More events and dashboards do not automatically create better decisions."] },
    ],
  },
  {
    slug: "canonical-tags-when-they-work",
    title: "Canonical tags: what they solve, what they merely suggest",
    description: "A canonical is a consolidation signal, not a cleanup crew. Use it for duplicates, not as a substitute for URL discipline.",
    category: "Technical SEO",
    format: "Explainer",
    series: "Technical baseline",
    readTime: "5 min read",
    published: "July 6, 2026",
    updated: "July 6, 2026",
    evidence: "Primary sources",
    audience: "Developers and technical marketers",
    keyTakeaways: ["Canonicals are hints, not directives", "Align links, sitemaps, redirects, and canonicals", "Fix avoidable duplication at the source"],
    verdict: "Canonical tags work best when every other site signal agrees with them.",
    sections: [
      { heading: "The job of a canonical", paragraphs: ["A canonical identifies the preferred representative among duplicate or substantially similar URLs. Search systems can use it to consolidate indexing and ranking signals."], bullets: ["Parameter variants", "Print or alternate views", "Syndicated or duplicated content", "Protocol and hostname variants"] },
      { heading: "Conflicts weaken the signal", paragraphs: ["A canonical that contradicts internal links, redirects, sitemap entries, or content similarity asks a search system to choose which instruction to trust.", "The durable fix is usually consistent URL behavior across the whole site."] },
      { heading: "When not to reach for it", paragraphs: ["Do not use canonicals to hide public pages, repair soft-404 behavior, or replace access controls. Each of those problems has a more direct mechanism."] },
    ],
  },
  {
    slug: "seo-migration-launch-checklist",
    title: "The no-drama SEO migration launch checklist",
    description: "A compact launch sequence for protecting valuable URLs, signals, measurement, and rollback options during a site move.",
    category: "Technical SEO",
    format: "Checklist",
    series: "Technical baseline",
    readTime: "9 min read",
    published: "July 5, 2026",
    updated: "July 5, 2026",
    evidence: "Documented practice",
    audience: "Developers and migration leads",
    keyTakeaways: ["Map valuable URLs before launch", "Test redirects as a graph", "Preserve a measurable rollback path"],
    verdict: "A migration succeeds when important old URLs resolve cleanly, measurement survives, and surprises are detected quickly.",
    sections: [
      { heading: "Before launch", paragraphs: ["Freeze an inventory of indexable URLs, traffic-bearing landing pages, backlinks, canonicals, titles, structured data, and analytics behavior."], bullets: ["Approve a one-to-one redirect map", "Crawl staging behind access control", "Verify production DNS and certificates", "Name the rollback owner"] },
      { heading: "At launch", paragraphs: ["Test representative URLs across every template and redirect rule. Confirm that production navigation, canonicals, robots rules, sitemaps, and measurement all reference the final hostname."] },
      { heading: "After launch", paragraphs: ["Monitor server errors, redirect chains, index coverage, Search Console signals, and revenue-critical landing pages. Triage by business consequence, not by raw error count."] },
    ],
  },
  {
    slug: "what-an-seo-report-should-answer",
    title: "Seven questions every SEO report should answer",
    description: "Reporting should reduce uncertainty and change decisions. If it only inventories activity, it is a receipt for busyness.",
    category: "Measurement",
    format: "Checklist",
    series: "Measurement without theater",
    readTime: "6 min read",
    published: "July 4, 2026",
    updated: "July 4, 2026",
    evidence: "Desk analysis",
    audience: "Marketing leads and clients",
    keyTakeaways: ["Connect work to observable change", "Name uncertainty and data limits", "End with the next decision"],
    verdict: "The best report makes the next operating decision easier, even when the result is disappointing.",
    sections: [
      { heading: "What changed?", paragraphs: ["Start with shipped work and external changes, then identify when each became observable. Activity without dates cannot be compared to outcomes."], bullets: ["What shipped?", "What moved?", "What did not move?", "What else changed?", "What remains uncertain?", "What did we learn?", "What happens next?"] },
      { heading: "What is the comparison?", paragraphs: ["Choose a baseline that fits the decision. Year-over-year, pre/post, matched pages, and controlled holdouts answer different questions."] },
      { heading: "What happens next?", paragraphs: ["Conclude with a decision, owner, timing, and expected signal. A report should be an operating instrument, not a monthly ceremony."] },
    ],
  },
  {
    slug: "ai-overviews-traffic-claims",
    title: "AI Overviews traffic claims: read the denominator",
    description: "Big percentage claims can hide tiny samples, unstable features, mismatched query sets, or traffic that was never commercially useful.",
    category: "Search landscape",
    format: "Claim check",
    series: "Claim checks",
    readTime: "7 min read",
    published: "July 3, 2026",
    updated: "July 3, 2026",
    evidence: "Desk analysis",
    audience: "Publishers and marketing leaders",
    keyTakeaways: ["Inspect the query sample", "Separate presence from causation", "Measure business exposure, not headlines"],
    verdict: "Treat broad traffic-impact claims as directional until the query set, period, geography, and counterfactual are visible.",
    sections: [
      { heading: "Start with the sample", paragraphs: ["Ask which queries were tracked, how they were selected, and whether the same result feature appeared throughout the measurement window."] },
      { heading: "Presence is not causation", paragraphs: ["An AI result can appear alongside seasonality, ranking movement, SERP redesigns, demand changes, and competitor gains. A correlation is a lead for investigation, not a finished causal claim."] },
      { heading: "Translate exposure into decisions", paragraphs: ["Segment queries by commercial role and page type. A change to low-value informational clicks may demand a different response than a change to qualified product discovery."] },
    ],
  },
  {
    slug: "local-seo-provider-scorecard",
    title: "A local SEO provider scorecard you can actually use",
    description: "Evaluate access, operating discipline, local evidence, reporting, and ownership before charisma gets a vote.",
    category: "Buyer defense",
    format: "Playbook",
    series: "Buying SEO",
    readTime: "8 min read",
    published: "July 2, 2026",
    updated: "July 2, 2026",
    evidence: "Documented practice",
    audience: "Local business owners",
    keyTakeaways: ["Score ownership and access first", "Ask for market-specific evidence", "Tie reporting to calls, bookings, and revenue"],
    verdict: "Choose the provider whose operating model remains legible after the sales call ends.",
    sections: [
      { heading: "Ownership before optimization", paragraphs: ["The business should control its domain, profiles, analytics, advertising accounts, call tracking, and core content. Providers can have delegated access without becoming the owner."] },
      { heading: "Evidence in the actual market", paragraphs: ["Ask how the provider evaluates location, service area, competition, review patterns, local landing pages, and map visibility for your specific business."], bullets: ["Named local competitors", "Representative non-branded queries", "Lead-quality definitions", "Profile change log"] },
      { heading: "A scorecard that survives procurement", paragraphs: ["Weight access, implementation responsibility, reporting clarity, correction policy, and contract exit terms. Treat case studies as context, not transferable guarantees."] },
    ],
  },
  {
    slug: "internal-links-audit-by-template",
    title: "Audit internal links by template, not one URL at a time",
    description: "The scalable unit of technical SEO is often the template. Find repeated link behavior before editing isolated pages.",
    category: "Technical SEO",
    format: "Playbook",
    series: "Technical baseline",
    readTime: "7 min read",
    published: "July 1, 2026",
    updated: "July 1, 2026",
    evidence: "Documented practice",
    audience: "Technical SEOs and developers",
    keyTakeaways: ["Group URLs by page template", "Measure link rules, not anecdotes", "Fix the highest-leverage component first"],
    verdict: "Template-level analysis turns internal linking from endless page editing into a maintainable system.",
    sections: [
      { heading: "Find repeated behavior", paragraphs: ["Cluster pages by the components that generate navigation, related content, breadcrumbs, pagination, and contextual links."] },
      { heading: "Compare intended and observed paths", paragraphs: ["Document which pages each template should make discoverable, then compare that intent to rendered links, crawl depth, orphan patterns, and anchor language."] },
      { heading: "Ship one rule, verify many pages", paragraphs: ["Prioritize changes that improve a repeated component. Sample the output after deployment and monitor for unintended links or crawl growth."] },
    ],
  },
  {
    slug: "zero-click-search-study-notes",
    title: "Zero-click studies: four numbers that change the story",
    description: "A data note on devices, query samples, result features, and the difference between fewer clicks and less opportunity.",
    category: "Search landscape",
    format: "Data note",
    series: "Reading the research",
    readTime: "6 min read",
    published: "July 1, 2026",
    updated: "July 1, 2026",
    evidence: "Desk analysis",
    audience: "Publishers and strategists",
    keyTakeaways: ["Separate mobile and desktop", "Inspect query-source bias", "Do not equate click share with business value"],
    verdict: "Zero-click rates describe measured behavior in a sample; they do not, by themselves, price the value of search to your business.",
    sections: [
      { heading: "Device mix", paragraphs: ["Mobile and desktop result pages differ in layout, features, and behavior. A blended rate can conceal the environment where the meaningful change occurred."] },
      { heading: "Query-source bias", paragraphs: ["Panel, browser, clickstream, and keyword-set studies observe different populations. The sample determines which kinds of searches can appear in the result."] },
      { heading: "Opportunity is not click share", paragraphs: ["Brand exposure, direct follow-on behavior, assisted conversions, and qualified commercial visits may move differently from total clicks. Use the study to frame a question, then inspect your own exposure."] },
    ],
  },
];

// Backward-compatible alias for the original field-note routes.
export const guides = articles;

export const glossary = [
  { term: "Canonical URL", slug: "canonical-url", category: "Technical", short: "The preferred URL a page declares when substantially similar versions can be reached at multiple addresses.", full: "A canonical is a hint about which URL should represent a group of duplicate or near-duplicate pages. It helps consolidate signals, but it is not a redirect and it does not override every conflicting signal.", myth: "A canonical tag does not remove a public page or force a search engine to index the selected URL." },
  { term: "Conversion", slug: "conversion", category: "Measurement", short: "A visitor action the business has deliberately defined as meaningful progress toward an outcome.", full: "A conversion might be a qualified form submission, completed booking, purchase, call, or another valuable action. Primary conversions should reflect business outcomes more closely than incidental clicks.", myth: "A button click is not necessarily a completed outcome, and more conversions are not better if lead quality collapses." },
  { term: "Crawling", slug: "crawling", category: "Discovery", short: "Automated retrieval and traversal of web resources for discovery, indexing, monitoring, or analysis.", full: "A crawler requests URLs, reads responses, and may follow links according to its purpose and policy. Technical crawls reveal observable structure, but the findings still require interpretation and a defined sample.", myth: "Crawling does not authorize bypassing authentication, access controls, provider terms, or privacy expectations." },
  { term: "Indexing", slug: "indexing", category: "Discovery", short: "A search system’s process of evaluating and storing information about a page for possible retrieval.", full: "After discovery and crawling, a search system may process a page and include information about it in an index. Accessibility, canonicalization, duplication, quality, directives, and system decisions all influence the outcome.", myth: "Indexing is not ranking. A page can be indexed and remain practically invisible for a query." },
  { term: "Google Search Console", slug: "google-search-console", category: "Measurement", short: "Google’s owner-facing service for monitoring and debugging how a verified site appears in Google Search.", full: "Search Console provides search-performance and technical reports for verified properties. Its data reflects Google Search, with dimensions, date ranges, quotas, sampling and interpretation limits.", myth: "Search Console is not Google Analytics and does not describe every on-site visit or business outcome." },
  { term: "XML sitemap", slug: "xml-sitemap", category: "Discovery", short: "A machine-readable list of canonical URLs a site wants eligible crawlers to discover.", full: "A sitemap can help search systems find important pages, especially on a new or large site. It should contain public, canonical, indexable URLs and stay consistent with the site’s navigation and directives.", myth: "Submitting a sitemap is not a ranking command and does not guarantee indexing." },
  { term: "robots.txt", slug: "robots-txt", category: "Technical", short: "A public top-level file that publishes crawl rules for automated clients following the Robots Exclusion Protocol.", full: "Cooperative crawlers use its allow and disallow rules when deciding which paths to request. The file is public and should never be treated as a place to hide sensitive routes.", myth: "robots.txt is not authentication and does not reliably keep a public URL out of search results." },
  { term: "Redirect", slug: "redirect", category: "Technical", short: "A response that tells a browser or crawler to request a resource at a different URL.", full: "Redirects preserve useful paths when URLs move. Permanent and temporary responses communicate different intent, and valuable old routes should map to the closest relevant destination.", myth: "Sending every removed URL to the homepage does not preserve relevance or repair a careless migration." },
  { term: "Search intent", slug: "search-intent", category: "Content", short: "The job a searcher appears to be trying to complete with a query.", full: "Intent is inferred from the wording, context, result set, and behavior around a query. Useful pages satisfy the underlying task instead of merely repeating the phrase.", myth: "Intent is not a fixed four-label taxonomy and can differ across people, moments, and result types." },
  { term: "Technical SEO", slug: "technical-seo", category: "Technical", short: "Work that makes a site easier for search systems to access, interpret, consolidate, and monitor.", full: "Technical SEO covers crawl paths, status codes, rendering, canonicals, structured data, sitemaps, internal linking, performance, and deployment behavior. Its purpose is to remove ambiguity and prevent technical loss.", myth: "A perfect tool score does not create demand, authority, useful content, or revenue by itself." },
  { term: "Web analytics", slug: "web-analytics", category: "Measurement", short: "The collection and interpretation of configured website activity for defined operating questions.", full: "Analytics tools record selected events and properties. The numbers depend on implementation, consent, filters, identity rules, and the quality of the event plan.", myth: "A dashboard is not automatically complete, causal, or connected to qualified customers." },
  { term: "Domain name", slug: "domain-name", category: "Ownership", short: "A human-readable name used to reach internet services, controlled through registration and DNS.", full: "Registration establishes control of the name for a period; DNS records direct website, email, verification, and other traffic. The domain, hosting, source code, and business email remain separate assets.", myth: "Moving a website does not necessarily require transferring the domain registration." },
];

export const experiments = [
  { id: "RB-EXP-001", title: "Direct titles vs. brand-led titles", status: "Measuring", hypothesis: "Direct, descriptive titles may establish clearer query alignment than brand-led titles on a young publication.", signal: "Impressions + query mix", window: "28 days" },
  { id: "RB-EXP-002", title: "Definition-first glossary pages", status: "Queued", hypothesis: "Putting the plain-language answer first may improve usefulness without forcing every entry into long-form article theater.", signal: "Indexation + engagement", window: "42 days" },
  { id: "RB-EXP-003", title: "Visible evidence labels", status: "Queued", hypothesis: "Readers may navigate more confidently when source depth and claim limits are visible before the body copy.", signal: "Navigation paths", window: "21 days" },
];
